#!/usr/bin/env python

import sys
import pickle
from pathlib import Path

path = str(Path.home())+'/.task_queue'
# Checking if there is more than 1 argument(s)
if len(sys.argv) > 1:
	queue = []
	#with open(path, 'wb+')  as file:
		#pickle.dump(queue, file)
	if sys.argv[1] == '-a': #-a for add task
		try:
			with open(path, 'rb') as file:
                        	queue = pickle.load(file)
		except Exception as e:
			pass
		if len(sys.argv) >= 3:
			queue.append(sys.argv[2])
		else:
			queue.append(input("Enter the task: "))
		with open(path, 'wb+') as file:
			pickle.dump(queue, file)
	elif sys.argv[1] == '-l': #for list all tasks with index
		with open(path, 'rb') as file:
			queue = pickle.load(file)
		for i in range(len(queue)-1,-1,-1):
			print(str((len(queue)-i))+') '+queue[i])
	elif sys.argv[1] == '-r': #for removing the most recently added task or a specifically indexed task
		with open(path, 'rb') as file:
			queue = pickle.load(file)
		if len(sys.argv) >=3:
			queue.pop(len(queue)-int(sys.argv[2]))
		else:
			queue.pop()
		with open(path, 'wb') as file:
			pickle.dump(queue, file)
	else:
		print('please enter a valid flag')
else:
	print('please provide arguments for tq')
